### PR TITLE
Introduce Apache RAT plugin in order to check license headers

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Comment by eolivelli** [comment]
@amitvc @aluccaroni 
any volounteer to finish the work ?

in order to run apache-rat just run on this branch

mvn apache-rat:check

**Comment by diegosalvi** [comment]
I have some problem with eclipse temp files, can we add some exclusions by path (like .gitignore)?

 !????? herddb-proto/.settings/org.eclipse.m2e.core.prefs
 !????? herddb-proto/.settings/org.eclipse.wst.validation.prefs
 !????? herddb-proto/.settings/org.eclipse.wst.common.component
 !????? herddb-proto/.settings/org.eclipse.jdt.core.prefs
 !????? herddb-proto/.settings/org.eclipse.wst.common.project.facet.core.xml
 !????? herddb-proto/.settings/org.eclipse.core.resources.prefs

**Comment by eolivelli** [comment]
@diegosalvi see parseSCMIgnoresAsExcludes, it is enabled by default
https://creadur.apache.org/rat/apache-rat-plugin/check-mojo.html#parseSCMIgnoresAsExcludes

**Comment by eolivelli** [comment]
@diegosalvi  in BookKeeper we have specific exclusions for Idea
https://github.com/apache/bookkeeper/blob/master/pom.xml#L938

but nothing for Eclipse and I know there are developers with Eclipse in BK community

**Comment by diegosalvi** [comment]
CI Failed :/
Too many files with unapproved license: 2 See RAT report in: /home/travis/build/diennea/herddb/target/rat.txt

**Comment by diegosalvi** [comment]
Added exclusions for Eclipse files

**Comment by eolivelli** [comment]
last two files:
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (default-cli) on project herddb-parent: Too many files with unapproved license: 2 See RAT report in: /home/travis/build/diennea/herddb/target/rat.txt -> [Help 1]

**Comment by eolivelli** [comment]
@amitvc this is a pending ticket, you could pick this up and finish the work

**Pull request closed without merging**
