### PR TITLE
Fix unordere BLink iteration during split

### PR DESCRIPTION
**Pull request by diegosalvi**
When iterating result during a node split some data is read in a wrong order

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by diegosalvi** [comment]
@eolivelli test in #496 was failing everytime?
I copyied suc test locally with this patch and i cannot record any failure (after fixing CREATE INDEX syntax in one test)

**Comment by eolivelli** [comment]
Wrong pr

**Comment by diegosalvi** [comment]
This one? #498

**Comment by eolivelli** [comment]
I confirm that my test is passing in this branch (and Travis confirmed!)

**Pull request merged**
