### PR TITLE
Upgrade calcite version to 1.19

### PR DESCRIPTION
**Pull request by amitvc**
This PR deals with upgrading herddb to use calcite 1.19. We initially tried upgrading to 1.20 but ran into lot of problems. There is an additional PR out there which consists changes needed for upgrading to 1.20.

### CODE REVIEW

**Comment by eolivelli** [comment]
Can you please compare the results for
mvn dependency:tree
On current master and on current master after applying the patch?
Maybe Calcite is importing new dependencies and we must be aware about it

**Comment by amitvc** [comment]
@eolivelli I am getting this error when I run dependencytree from the root.
Failed to execute goal on project herddb-net: Could not resolve dependencies for project org.herddb:herddb-net:jar:0.12.0-SNAPSHOT: Could not find artifact org.herddb:herddb-utils:jar:0.12.0-SNAPSHOT -> [Help 1]

**Comment by eolivelli** [comment]
You have to perform a full build.
mvn clean install -DskipTests

Master moved to 0.12.0-SNAPSHOT

**Comment by amitvc** [comment]
Here is the diff -
Calcite has upgraded a few things and also imported few new dependencies
See diff below


188,195c188,198
< [INFO] +- org.apache.calcite:calcite-core:jar:1.17.0:compile
< [INFO] |  +- org.apache.calcite.avatica:avatica-core:jar:1.12.0:compile
< [INFO] |  |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.12.0:compile
< [INFO] |  +- org.apache.calcite:calcite-linq4j:jar:1.17.0:compile
< [INFO] |  +- org.apache.commons:commons-dbcp2:jar:2.4.0:compile
< [INFO] |  +- org.apache.commons:commons-pool2:jar:2.6.1:compile
< [INFO] |  +- org.codehaus.janino:janino:jar:2.7.6:compile
< [INFO] |  \- org.codehaus.janino:commons-compiler:jar:2.7.6:compile
---
> [INFO] +- org.apache.calcite:calcite-core:jar:1.19.0:compile
> [INFO] |  +- org.apache.calcite.avatica:avatica-core:jar:1.13.0:compile
> [INFO] |  |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.13.0:compile
> [INFO] |  +- org.apache.calcite:calcite-linq4j:jar:1.19.0:compile
> [INFO] |  +- org.apache.commons:commons-dbcp2:jar:2.5.0:compile
> [INFO] |  |  \- org.apache.commons:commons-pool2:jar:2.6.1:compile
> [INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8:compile
> [INFO] |  |  \- org.yaml:snakeyaml:jar:1.23:compile
> [INFO] |  +- com.jayway.jsonpath:json-path:jar:2.4.0:compile
> [INFO] |  +- org.codehaus.janino:janino:jar:3.0.11:compile
> [INFO] |  \- org.codehaus.janino:commons-compiler:jar:3.0.11:compile
271,277c274,283
< [INFO] |  \- org.apache.calcite:calcite-core:jar:1.17.0:compile
< [INFO] |     +- org.apache.calcite.avatica:avatica-core:jar:1.12.0:compile
< [INFO] |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.12.0:compile
< [INFO] |     +- org.apache.calcite:calcite-linq4j:jar:1.17.0:compile
< [INFO] |     +- org.apache.commons:commons-dbcp2:jar:2.4.0:compile
< [INFO] |     +- org.codehaus.janino:janino:jar:2.7.6:compile
< [INFO] |     \- org.codehaus.janino:commons-compiler:jar:2.7.6:compile
---
> [INFO] |  \- org.apache.calcite:calcite-core:jar:1.19.0:compile
> [INFO] |     +- org.apache.calcite.avatica:avatica-core:jar:1.13.0:compile
> [INFO] |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.13.0:compile
> [INFO] |     +- org.apache.calcite:calcite-linq4j:jar:1.19.0:compile
> [INFO] |     +- org.apache.commons:commons-dbcp2:jar:2.5.0:compile
> [INFO] |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8:compile
> [INFO] |     |  \- org.yaml:snakeyaml:jar:1.23:compile
> [INFO] |     +- com.jayway.jsonpath:json-path:jar:2.4.0:compile
> [INFO] |     +- org.codehaus.janino:janino:jar:3.0.11:compile
> [INFO] |     \- org.codehaus.janino:commons-compiler:jar:3.0.11:compile
305c311
< [INFO] +- org.apache.calcite:calcite-linq4j:jar:1.17.0:compile
---
> [INFO] +- org.apache.calcite:calcite-linq4j:jar:1.19.0:compile
379,385c385,394
< [INFO] |  |  \- org.apache.calcite:calcite-core:jar:1.17.0:compile
< [INFO] |  |     +- org.apache.calcite.avatica:avatica-core:jar:1.12.0:compile
< [INFO] |  |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.12.0:compile
< [INFO] |  |     +- org.apache.calcite:calcite-linq4j:jar:1.17.0:compile
< [INFO] |  |     +- org.apache.commons:commons-dbcp2:jar:2.4.0:compile
< [INFO] |  |     +- org.codehaus.janino:janino:jar:2.7.6:compile
< [INFO] |  |     \- org.codehaus.janino:commons-compiler:jar:2.7.6:compile
---
> [INFO] |  |  \- org.apache.calcite:calcite-core:jar:1.19.0:compile
> [INFO] |  |     +- org.apache.calcite.avatica:avatica-core:jar:1.13.0:compile
> [INFO] |  |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.13.0:compile
> [INFO] |  |     +- org.apache.calcite:calcite-linq4j:jar:1.19.0:compile
> [INFO] |  |     +- org.apache.commons:commons-dbcp2:jar:2.5.0:compile
> [INFO] |  |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8:compile
> [INFO] |  |     |  \- org.yaml:snakeyaml:jar:1.23:compile
> [INFO] |  |     +- com.jayway.jsonpath:json-path:jar:2.4.0:compile
> [INFO] |  |     +- org.codehaus.janino:janino:jar:3.0.11:compile
> [INFO] |  |     \- org.codehaus.janino:commons-compiler:jar:3.0.11:compile
482,488c491,500
< [INFO] |  |  \- org.apache.calcite:calcite-core:jar:1.17.0:compile
< [INFO] |  |     +- org.apache.calcite.avatica:avatica-core:jar:1.12.0:compile
< [INFO] |  |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.12.0:compile
< [INFO] |  |     +- org.apache.calcite:calcite-linq4j:jar:1.17.0:compile
< [INFO] |  |     +- org.apache.commons:commons-dbcp2:jar:2.4.0:compile
< [INFO] |  |     +- org.codehaus.janino:janino:jar:2.7.6:compile
< [INFO] |  |     \- org.codehaus.janino:commons-compiler:jar:2.7.6:compile
---
> [INFO] |  |  \- org.apache.calcite:calcite-core:jar:1.19.0:compile
> [INFO] |  |     +- org.apache.calcite.avatica:avatica-core:jar:1.13.0:compile
> [INFO] |  |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.13.0:compile
> [INFO] |  |     +- org.apache.calcite:calcite-linq4j:jar:1.19.0:compile
> [INFO] |  |     +- org.apache.commons:commons-dbcp2:jar:2.5.0:compile
> [INFO] |  |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8:compile
> [INFO] |  |     |  \- org.yaml:snakeyaml:jar:1.23:compile
> [INFO] |  |     +- com.jayway.jsonpath:json-path:jar:2.4.0:compile
> [INFO] |  |     +- org.codehaus.janino:janino:jar:3.0.11:compile
> [INFO] |  |     \- org.codehaus.janino:commons-compiler:jar:3.0.11:compile
538,544c550,559
< [INFO] |  \- org.apache.calcite:calcite-core:jar:1.17.0:compile
< [INFO] |     +- org.apache.calcite.avatica:avatica-core:jar:1.12.0:compile
< [INFO] |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.12.0:compile
< [INFO] |     +- org.apache.calcite:calcite-linq4j:jar:1.17.0:compile
< [INFO] |     +- org.apache.commons:commons-dbcp2:jar:2.4.0:compile
< [INFO] |     +- org.codehaus.janino:janino:jar:2.7.6:compile
< [INFO] |     \- org.codehaus.janino:commons-compiler:jar:2.7.6:compile
---
> [INFO] |  \- org.apache.calcite:calcite-core:jar:1.19.0:compile
> [INFO] |     +- org.apache.calcite.avatica:avatica-core:jar:1.13.0:compile
> [INFO] |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.13.0:compile
> [INFO] |     +- org.apache.calcite:calcite-linq4j:jar:1.19.0:compile
> [INFO] |     +- org.apache.commons:commons-dbcp2:jar:2.5.0:compile
> [INFO] |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8:compile
> [INFO] |     |  \- org.yaml:snakeyaml:jar:1.23:compile
> [INFO] |     +- com.jayway.jsonpath:json-path:jar:2.4.0:compile
> [INFO] |     +- org.codehaus.janino:janino:jar:3.0.11:compile
> [INFO] |     \- org.codehaus.janino:commons-compiler:jar:3.0.11:compile
695,701c710,719
< [INFO] |  |  \- org.apache.calcite:calcite-core:jar:1.17.0:compile
< [INFO] |  |     +- org.apache.calcite.avatica:avatica-core:jar:1.12.0:compile
< [INFO] |  |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.12.0:compile
< [INFO] |  |     +- org.apache.calcite:calcite-linq4j:jar:1.17.0:compile
< [INFO] |  |     +- org.apache.commons:commons-dbcp2:jar:2.4.0:compile
< [INFO] |  |     +- org.codehaus.janino:janino:jar:2.7.6:compile
< [INFO] |  |     \- org.codehaus.janino:commons-compiler:jar:2.7.6:compile
---
> [INFO] |  |  \- org.apache.calcite:calcite-core:jar:1.19.0:compile
> [INFO] |  |     +- org.apache.calcite.avatica:avatica-core:jar:1.13.0:compile
> [INFO] |  |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.13.0:compile
> [INFO] |  |     +- org.apache.calcite:calcite-linq4j:jar:1.19.0:compile
> [INFO] |  |     +- org.apache.commons:commons-dbcp2:jar:2.5.0:compile
> [INFO] |  |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8:compile
> [INFO] |  |     |  \- org.yaml:snakeyaml:jar:1.23:compile
> [INFO] |  |     +- com.jayway.jsonpath:json-path:jar:2.4.0:compile
> [INFO] |  |     +- org.codehaus.janino:janino:jar:3.0.11:compile
> [INFO] |  |     \- org.codehaus.janino:commons-compiler:jar:3.0.11:compile
807,813c825,834
< [INFO] |  |  \- org.apache.calcite:calcite-core:jar:1.17.0:runtime
< [INFO] |  |     +- org.apache.calcite.avatica:avatica-core:jar:1.12.0:runtime
< [INFO] |  |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.12.0:runtime
< [INFO] |  |     +- org.apache.calcite:calcite-linq4j:jar:1.17.0:runtime
< [INFO] |  |     +- org.apache.commons:commons-dbcp2:jar:2.4.0:runtime
< [INFO] |  |     +- org.codehaus.janino:janino:jar:2.7.6:runtime
< [INFO] |  |     \- org.codehaus.janino:commons-compiler:jar:2.7.6:runtime
---
> [INFO] |  |  \- org.apache.calcite:calcite-core:jar:1.19.0:runtime
> [INFO] |  |     +- org.apache.calcite.avatica:avatica-core:jar:1.13.0:runtime
> [INFO] |  |     |  \- org.apache.calcite.avatica:avatica-metrics:jar:1.13.0:runtime
> [INFO] |  |     +- org.apache.calcite:calcite-linq4j:jar:1.19.0:runtime
> [INFO] |  |     +- org.apache.commons:commons-dbcp2:jar:2.5.0:runtime
> [INFO] |  |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.8:runtime
> [INFO] |  |     |  \- org.yaml:snakeyaml:jar:1.23:runtime
> [INFO] |  |     +- com.jayway.jsonpath:json-path:jar:2.4.0:runtime
> [INFO] |  |     +- org.codehaus.janino:janino:jar:3.0.11:runtime
> [INFO] |  |     \- org.codehaus.janino:commons-compiler:jar:3.0.11:runtime
824,834c845,855
< [INFO] Herd DB ............................................ SUCCESS [  0.342 s]
< [INFO] HerdDB Utils ....................................... SUCCESS [  0.022 s]
< [INFO] HerdDB Networking .................................. SUCCESS [  0.131 s]
< [INFO] HerdDB Core ........................................ SUCCESS [  0.340 s]
< [INFO] HerdDB JDBC Driver ................................. SUCCESS [  0.035 s]
< [INFO] HerdDB Collections Framework. ...................... SUCCESS [  0.008 s]
< [INFO] HerdDB UI .......................................... SUCCESS [  0.080 s]
< [INFO] HerdDB CLI ......................................... SUCCESS [  0.032 s]
< [INFO] HerdDB Services .................................... SUCCESS [  0.104 s]
< [INFO] HerdDB Benchmarks .................................. SUCCESS [  0.022 s]
< [INFO] HerdDB Website ..................................... SUCCESS [  0.007 s]
---
> [INFO] Herd DB ............................................ SUCCESS [  0.448 s]
> [INFO] HerdDB Utils ....................................... SUCCESS [  0.027 s]
> [INFO] HerdDB Networking .................................. SUCCESS [  0.189 s]
> [INFO] HerdDB Core ........................................ SUCCESS [  0.460 s]
> [INFO] HerdDB JDBC Driver ................................. SUCCESS [  0.049 s]
> [INFO] HerdDB Collections Framework. ...................... SUCCESS [  0.010 s]
> [INFO] HerdDB UI .......................................... SUCCESS [  0.094 s]
> [INFO] HerdDB CLI ......................................... SUCCESS [  0.037 s]
> [INFO] HerdDB Services .................................... SUCCESS [  0.150 s]
> [INFO] HerdDB Benchmarks .................................. SUCCESS [  0.024 s]
> [INFO] HerdDB Website ..................................... SUCCESS [  0.009 s]
836c857
< [INFO] HerdDB Backward compatibility tests ................ SUCCESS [  0.020 s]
---
> [INFO] HerdDB Backward compatibility tests ................ SUCCESS [  0.022 s]
840,842c861,863
< [INFO] Total time: 1.924 s
< [INFO] Finished at: 2019-07-25T23:36:05-07:00
< [INFO] Final Memory: 22M/84M
---
> [INFO] Total time: 2.374 s
> [INFO] Finished at: 2019-07-25T23:33:56-07:00
> [INFO] Final Memory: 22M/80M

**Comment by diegosalvi** [comment]
Yes we can merge this.
No cherry pick, better to have more time for testing :D

**Pull request merged**
