### PR TITLE
Fix race condition during checkpoint

### PR DESCRIPTION
**Pull request by eolivelli**
- During checkpoint we must ensure that records are always reachable from what is present in the PK index
- Add a table wise metric to track this case

### CODE REVIEW

**Comment by eolivelli** [comment]
Tests are still failing

**Comment by eolivelli** [comment]
@diegosalvi  this is the error with the new debug

> java.util.concurrent.ExecutionException: java.lang.RuntimeException: herddb.model.StatementExecutionException: herddb.storage.DataStorageManagerException: inconsistency! table mytable no record in memory for 746573745f31353139 page 71, activePages {64=[10082,160,2400], 65=[10091,160,2240], 66=[10124,160,2880], 67=[10099,160,2080], 68=[10116,160,3040], 69=[10099,160,800], 70=[10125,160,1280], 71=[10119,165,2475], 72=[10099,160,1920], 73=[10111,160,2400], 74=[10108,160,1600], 75=[10106,160,2400], 76=[10112,160,1280], 77=[10106,160,2560], 78=[10104,162,1782], 79=[10105,160,1760], 80=[3365,160,800], 81=[10107,160,1760], 82=[10110,160,480], 83=[10110,160,1600], 84=[10102,160,480], 85=[10109,160,160], 86=[10114,160,0], 47=[10112,160,4000], 48=[10107,160,4320], 49=[10107,160,3360], 50=[10106,160,3680], 51=[10115,160,3680], 52=[10098,160,3200], 53=[10116,160,3520], 54=[10102,160,2560], 55=[10112,160,3360], 56=[10116,160,2560], 57=[10112,160,1920], 58=[5615,160,2240], 59=[10096,160,1600], 60=[10106,160,1760], 61=[10106,160,1920], 62=[10139,160,1440], 63=[10110,160,3200]}, dataPage DataPage{pageId=71, immutable=true, writable=false, usedMemory=9797}, dataPageKeys =[746573745f31393433, 746573745f31393430, 746573745f363333, 746573745f373535, 746573745f31393436, 746573745f393932, 746573745f333130, 746573745f31373038, 746573745f393930, 746573745f31373036, 746573745f31393438, 746573745f3733, 746573745f3739, 746573745f32, 746573745f31363633, 746573745f31393830, 746573745f31353134, 746573745f31393938, 746573745f31313138, 746573745f31353133, 746573745f31393937, 746573745f31393533, 746573745f31353132, 746573745f31393532, 746573745f31393935, 746573745f31353131, 746573745f363232, 746573745f31393538, 746573745f31353137, 746573745f31393537, 746573745f343636, 746573745f31393536, 746573745f313034, 746573745f31393535, 746573745f3437, 746573745f31393930, 746573745f31323733, 746573745f31343333, 746573745f31353130, 746573745f31393530, 746573745f31353936, 746573745f31393230, 746573745f31303439, 746573745f31393633, 746573745f31323033, 746573745f31383039, 746573745f383137, 746573745f31313232, 746573745f343036, 746573745f363035, 746573745f31333739, 746573745f363434, 746573745f31383134, 746573745f31383537, 746573745f3236, 746573745f353632, 746573745f31313731, 746573745f31303534, 746573745f31303936, 746573745f31323133, 746573745f31303539] after many trials

how is it possible that the record is missing from an **immutable=true** page ?

**Comment by diegosalvi** [comment]
Rally strange. No immutabile pages can be altered. But a page could be replaced with an immutabile version meantime

**Comment by eolivelli** [comment]
@diegosalvi
I think I found two other problems but I don't have my PC now.

During checkpoint there is a loop on which we are not taking the lock for buildingPage.

And at the beginning of the checkpoint procedure we are removing pages from 'pages' too early, that is before relocating the records to other pages.

The errors on Travis seen after my last debug tell that fetchRecord is looking gor a record into a page that never seen it before (see the new debug variable I added to DataPage)

**Comment by eolivelli** [comment]
@diegosalvi 
I have created a job on our jenkins in order to keep logs:
https://dev.majordodo.org/jenkins/job/HerdDB-FixCheckpoint/

**Comment by eolivelli** [comment]
This is one error: we are looking for 746573745f373335  in page 57 but page 57 (immutable) never seen such key

[ERROR] Tests run: 8, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 44.16 s <<< FAILURE! - in herddb.server.hammer.DirectMultipleConcurrentUpdatesTest
[ERROR] testWithTransactionsWithCheckpoints(herddb.server.hammer.DirectMultipleConcurrentUpdatesTest)  Time elapsed: 15.042 s  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.RuntimeException: herddb.model.StatementExecutionException: herddb.storage.DataStorageManagerException: inconsistency! table mytable no record in memory for 746573745f373335 page 57, activePages {64=[10110,160,2080], 65=[10111,160,2400], 66=[10091,160,2720], 67=[10111,160,2400], 68=[10109,160,800], 69=[10114,160,2560], 70=[10109,160,2080], 71=[10088,160,1760], 72=[10111,160,1600], 73=[10116,160,1760], 74=[10115,160,2080], 76=[10105,160,1920], 77=[10102,160,160], 78=[10094,160,1600], 79=[10103,160,640], 80=[10108,160,960], 41=[10102,160,4000], 43=[10104,160,3200], 44=[10104,160,3680], 45=[10105,160,3040], 46=[10109,160,3200], 47=[10100,160,2400], 48=[10110,160,2880], 49=[10112,160,1280], 50=[10112,160,2240], 51=[3048,160,1760], 52=[10128,160,1920], 53=[10118,160,1280], 54=[10084,160,2080], 55=[10122,160,2080], 56=[10125,160,2080], 57=[10105,162,1944], 58=[10094,160,3040], 59=[10095,160,1280], 60=[10120,160,1760], 61=[10106,160,1920], 62=[10110,160,2080], 63=[10106,160,2400]}, dataPage DataPage{pageId=57, immutable=true, writable=false, usedMemory=9945, debugSeenKeys [746573745f393132, 746573745f31373030, 746573745f383333, 746573745f383733, 746573745f323336, 746573745f31383238, 746573745f313532, 746573745f3331, 746573745f31373830, 746573745f373138, 746573745f31323233, 746573745f343639, 746573745f373431, 746573745f343634, 746573745f313834, 746573745f31313934, 746573745f3437, 746573745f31333531, 746573745f31363730, 746573745f31333532, 746573745f31333934, 746573745f31313532, 746573745f31353938, 746573745f31333535, 746573745f31333536, 746573745f31333533, 746573745f31333236, 746573745f373337, 746573745f373334, 746573745f31333234, 746573745f373333, 746573745f343131, 746573745f31333238, 746573745f31343439, 746573745f363531, 746573745f333332, 746573745f3539, 746573745f333732, 746573745f3935, 746573745f3531, 746573745f31323431, 746573745f31383535, 746573745f383031, 746573745f353233, 746573745f363030, 746573745f353234, 746573745f31393335, 746573745f393634, 746573745f353231, 746573745f353232, 746573745f31393339, 746573745f313635, 746573745f31383931, 746573745f31313332, 746573745f31303535, 746573745f31313330, 746573745f31313335, 746573745f31313336, 746573745f393238, 746573745f353239, 746573745f31313333, 746573745f31313334]}, dataPageKeys =[746573745f393132, 746573745f31373030, 746573745f383333, 746573745f383733, 746573745f323336, 746573745f31383238, 746573745f313532, 746573745f3331, 746573745f31373830, 746573745f373138, 746573745f31323233, 746573745f343639, 746573745f373431, 746573745f343634, 746573745f313834, 746573745f31313934, 746573745f3437, 746573745f31333531, 746573745f31363730, 746573745f31333532, 746573745f31333934, 746573745f31313532, 746573745f31353938, 746573745f31333535, 746573745f31333536, 746573745f31333533, 746573745f31333236, 746573745f373337, 746573745f373334, 746573745f31333234, 746573745f373333, 746573745f343131, 746573745f31333238, 746573745f31343439, 746573745f363531, 746573745f333332, 746573745f3539, 746573745f333732, 746573745f3935, 746573745f3531, 746573745f31323431, 746573745f31383535, 746573745f383031, 746573745f353233, 746573745f363030, 746573745f353234, 746573745f31393335, 746573745f393634, 746573745f353231, 746573745f353232, 746573745f31393339, 746573745f313635, 746573745f31383931, 746573745f31313332, 746573745f31303535, 746573745f31313330, 746573745f31313335, 746573745f31313336, 746573745f393238, 746573745f353239, 746573745f31313333, 746573745f31313334] after many trials

**Comment by diegosalvi** [comment]
The loop whitout lock isn't a problem. It was needed only for dirty pages due to the write on pk before page

**Comment by diegosalvi** [comment]
Thinking about the record never seen in data page i think is related to mutable  to immutabile page conversion while flushing the page. Knowing that the page cannot be modified anymore it is replaced with an immutabile version (checks against immutable  are simpler and  faster)

**Comment by eolivelli** [comment]
Feel free to add commit to this branch.
I tried to change toImmutable() but without success.
Can we revert that part of the change?

**Comment by diegosalvi** [comment]
We can avoid to invoke toImmutable but I think that the problem will remain just your debugger will work as expected. We could readd toImmutable invocation after bug resolution

**Comment by eolivelli** [comment]
@diegosalvi as expected the error is the same

ERROR] testWithTransactionsWithCheckpoints(herddb.server.hammer.DirectMultipleConcurrentUpdatesTest)  Time elapsed: 16.038 s  <<< ERROR!
herddb.model.StatementExecutionException: herddb.storage.DataStorageManagerException: inconsistency! table mytable no record in memory for 746573745f31323639 page 88, activePages {74=[10113,160,0], 75=[10104,160,0], 76=[10115,160,0], 77=[10117,160,0], 78=[10110,160,0], 79=[10113,160,0], 80=[10107,160,0], 81=[10112,160,0], 82=[10106,160,0], 83=[10101,160,0], 84=[10110,160,0], 85=[10114,160,0], 86=[644,161,0], 87=[10101,160,0], 88=[10105,162,0], 89=[10106,160,0], 90=[10117,160,0], 91=[10118,160,0], 92=[10115,160,0], 93=[10103,160,0], 94=[10097,160,0], 95=[10114,160,0], 96=[10118,160,0], 97=[10099,160,0], 98=[10105,160,0], 99=[10099,160,0], 100=[10104,160,0], 101=[10103,160,0], 102=[10114,160,0], 103=[10107,160,0], 104=[10089,160,0], 60=[10114,160,2400]}, dataPage DataPage{pageId=88, immutable=true, writable=false, usedMemory=9944, debugSeenKeys [746573745f353136, 746573745f31383635, 746573745f393534, 746573745f343335, 746573745f31393033, 746573745f373938, 746573745f31353034, 746573745f31393838, 746573745f373933, 746573745f3734, 746573745f3737, 746573745f31323230, 746573745f31353831, 746573745f31353837, 746573745f31383631, 746573745f373136, 746573745f353139, 746573745f31313435, 746573745f31343337, 746573745f31393534, 746573745f393839, 746573745f393435, 746573745f333439, 746573745f31333537, 746573745f363638, 746573745f373837, 746573745f343639, 746573745f343634, 746573745f343631, 746573745f323633, 746573745f31303731, 746573745f31333132, 746573745f31303037, 746573745f31343437, 746573745f393739, 746573745f31333234, 746573745f363131, 746573745f323539, 746573745f343134, 746573745f31363035, 746573745f31343035, 746573745f313333, 746573745f343932, 746573745f313733, 746573745f323039, 746573745f31373333, 746573745f353238, 746573745f31363535, 746573745f31343139, 746573745f343437, 746573745f323030, 746573745f313231, 746573745f353631, 746573745f323836, 746573745f3239, 746573745f31393337, 746573745f363038, 746573745f31353735, 746573745f363039, 746573745f31383934, 746573745f31353330, 746573745f31383932]}, dataPageKeys =[746573745f353136, 746573745f31383635, 746573745f393534, 746573745f343335, 746573745f31393033, 746573745f373938, 746573745f31353034, 746573745f31393838, 746573745f373933, 746573745f3734, 746573745f3737, 746573745f31323230, 746573745f31353831, 746573745f31353837, 746573745f31383631, 746573745f373136, 746573745f353139, 746573745f31313435, 746573745f31343337, 746573745f31393534, 746573745f393839, 746573745f393435, 746573745f333439, 746573745f31333537, 746573745f363638, 746573745f373837, 746573745f343639, 746573745f343634, 746573745f343631, 746573745f323633, 746573745f31303731, 746573745f31333132, 746573745f31303037, 746573745f31343437, 746573745f393739, 746573745f31333234, 746573745f363131, 746573745f323539, 746573745f343134, 746573745f31363035, 746573745f31343035, 746573745f313333, 746573745f343932, 746573745f313733, 746573745f323039, 746573745f31373333, 746573745f353238, 746573745f31363535, 746573745f31343139, 746573745f343437, 746573745f323030, 746573745f313231, 746573745f353631, 746573745f323836, 746573745f3239, 746573745f31393337, 746573745f363038, 746573745f31353735, 746573745f363039, 746573745f31383934, 746573745f31353330, 746573745f31383932] after many trials
	at herddb.core.DBManager.executePlan(DBManager.java:675)
	at herddb.core.TestUtils.scan(TestUtils.java:71)
	at herddb.server.hammer.DirectMultipleConcurrentUpdatesTest.performTest(DirectMultipleConcurrentUpdatesTest.java:252)
	at herddb.server.hammer.DirectMultipleConcurrentUpdatesTest.testWithTransactionsWithCheckpoints(DirectMultipleConcurrentUpdatesTest.java:87)

**Comment by diegosalvi** [comment]
Mmm being  immutable without toImmutable jeans that the page was reloaded the reloaded again mmm

**Comment by eolivelli** [comment]
@diegosalvi I have pushed a set of changes

**Comment by diegosalvi** [comment]
A concurrent on immutable I think it add just concurrent overhead. Every immutable page is built    with full data set and before sharing it

**Comment by eolivelli** [comment]
@diegosalvi I know.
I was only trying.
Thank you for keeping an eye

**Comment by diegosalvi** [comment]
I was thinking about adding a debug to fully track records during checkpoint (to remove later) to try to track down bug origin. I really don't understand what is causing it

**Comment by eolivelli** [comment]
@diegosalvi

See the logs on jenkins on you will be surprised!
The error is not during the checkpoint but after the reboot of the server.

So during checkpoint we are corrupting data

**Comment by diegosalvi** [comment]
It is related to a checkpoint but in a "strange way". The test RestartTest.recoverTableCreatedInTransaction create a new table, add a record and commit the transaction.
Before transaction commit it request a checkpoint too. This procedure create a TableSpace checkpoint for position 1.2. After commit another checkpoint is issued only for the new Table. Such checkpoints cover position 1.3 (with transaction commit).

On reboot TableSpace is loaded using log position 1.2 but table & index data exists for position 1.3 only and then it fails :(

**Comment by eolivelli** [comment]
Why this problem is not on 0.8?

I guess because we are more eagerly rewriting small pages

**Comment by diegosalvi** [comment]
I really don't know why isn't in 0.8 but it isn't related to smallpages at all but to checkpoint files:
tablespace was checkpointed at 1.2 but table have a checkpoint at 1.3 (at 1.2 didn't really existed and was skipped) and when we try to restore the table we load with a 1.3 checkpoint but we apply commit log from 1.2 (with a double commit).

Is possible that now it breaks due to some more checks on pk state that wasn't there before but the error is on the restore not the checkpoint itself

**Pull request closed without merging**
