### PR TITLE
Update ZooKeeper to 3.6.1

### PR DESCRIPTION
**Pull request by eolivelli**
Switch to ZK 3.6.1 client

### CODE REVIEW

**Comment by eolivelli** [comment]
@mino181295  we should make a similar fix in BookKeeper Visual Manager.
Because ZooKeeper Server needs Snappy and Dropwizard on the class path.

**Comment by eolivelli** [comment]
see https://github.com/apache/bookkeeper/issues/2292

**Comment by mino181295** [comment]
I think curator does not support Zookeeper 3.6.0 in 4.x

It will be supported in 5
https://github.com/apache/curator/commit/7bbb7196173b88baac0e102bdff265dc7f2ee77e

**Comment by eolivelli** [comment]
We are not using Curator @mino181295 in this project.
If we are using it in BKVM we can drop it, maybe it is only for tests

**Comment by eolivelli** [comment]
It looks like that with ZK 6.3.1 we do not have any more the problem with BK
https://github.com/apache/zookeeper/pull/1287

cc @dmercuriali @mino181295

**Comment by eolivelli** [comment]
@mino181295 @amitvc @diegosalvi this patch is ready for merge

**Comment by mino181295** [comment]
LGTM

**Comment by eolivelli** [comment]
thank you @mino181295 
I am merging this change now

**Pull request merged**
