### PR TITLE
Add OpenJPA Compatibility

### LINKED ISSUE #634: Something fishy with openjpa
**QUESTION**

I wanted to give a try with openjpa but I got several issues and one is that the DDL do not seem to work:

```
Caused by: org.apache.openjpa.lib.jdbc.ReportingSQLException: herddb.model.TableAlreadyExistsException: openjpa_sequence_table
	at herddb.core.TableSpaceManager.createTable(TableSpaceManager.java:1458)
	at herddb.core.TableSpaceManager.executeStatementAsyncInternal(TableSpaceManager.java:1282)
	at herddb.core.TableSpaceManager.executeStatementAsync(TableSpaceManager.java:1238)
	at herddb.core.DBManager.executeStatementAsync(DBManager.java:662)
	at herddb.core.DBManager.executePlanAsync(DBManager.java:719)
	at herddb.server.ServerSideConnectionPeer.handleExecuteStatement(ServerSideConnectionPeer.java:722)
	at herddb.server.ServerSideConnectionPeer.requestReceived(ServerSideConnectionPeer.java:139)
	at herddb.network.netty.NettyChannel.lambda$handlePduRequest$0(NettyChannel.java:97)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
 {stmnt 609116570 CREATE TABLE OPENJPA_SEQUENCE_TABLE (ID TINYINT NOT NULL, SEQUENCE_VALUE BIGINT, PRIMARY KEY (ID))} [code=0, state=null]
```

Here is my pom:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.example</groupId>
  <artifactId>test-herdb</artifactId>
  <version>1.0-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.12</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.openjpa</groupId>
      <artifactId>openjpa</artifactId>
      <version>3.1.1</version>
    </dependency>
    <dependency>
      <groupId>org.herddb</groupId>
      <artifactId>herddb-jdbc</artifactId>
      <version>0.16.1</version>
    </dependency>
  </dependencies>
  <build>
    <plugins><plugin>
      <groupId>org.apache.openjpa</groupId>
      <artifactId>openjpa-maven-plugin</artifactId>
      <version>3.1.1</version>
      <executions>
        <execution>
          <id>enhancer</id>
          <phase>compile</phase>
          <goals>
            <goal>enhance</goal>
          </goals>
          <configuration>
            <toolProperties>
              <MetaDataFactory>jpa</MetaDataFactory>
            </toolProperties>
          </configuration>
        </execution>
      </executions>
      <configuration>
        <includes>test/entity/*.class</includes>
        <sqlAction>build</sqlAction>
        <toolProperties>
          <MappingDefaults>jpa(ForeignKeyDeleteAction=restrict,JoinForeignKeyDeleteAction=restrict)</MappingDefaults>
          <MetaDataFactory>jpa</MetaDataFactory>
        </toolProperties>
      </configuration>
    </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <release>11</release>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

My entity:

```
package test.entity;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
public class User {
    @Id
    @GeneratedValue
    private long id;
    private String name;
    //@Lob
    private String description;
}
```

The test main:

```
package test;
import herddb.server.Server;
import herddb.server.ServerConfiguration;
import org.apache.bookkeeper.stats.NullStatsLogger;
import test.entity.User;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
public class Main {
    public static void main(String[] args) throws Exception {
        final Server server = new Server(new ServerConfiguration(), new NullStatsLogger());
        server.start();
        final EntityManagerFactory factory = Persistence.createEntityManagerFactory("hdb");
        {
            final EntityManager em = factory.createEntityManager();
            final EntityTransaction transaction = em.getTransaction();
            transaction.begin();
            em.persist(new User(0, "First", "Something"));
            transaction.commit();
            em.close();
        }
        {
            final EntityManager em = factory.createEntityManager();
            System.out.println(em.createQuery("select e from User e").getResultList());
            em.close();
        }
        factory.close();
        server.close();
    }
}
```

and the persistence descriptor:

```
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.1"
             xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd">
  <persistence-unit name="hdb" transaction-type="RESOURCE_LOCAL">
    <class>test.entity.User</class>
    <exclude-unlisted-classes>true</exclude-unlisted-classes>
    <properties>
      <property name="javax.persistence.jdbc.driver" value="herddb.jdbc.Driver" />
      <property name="javax.persistence.jdbc.url" value="jdbc:herddb:server:localhost:7000" />
      <property name="javax.persistence.jdbc.user" value="sa" />
      <property name="javax.persistence.jdbc.password" value="hdb" />
      <property name="javax.persistence.schema-generation.database.action" value="drop-and-create" />
      <property name="openjpa.jdbc.DBDictionary" value="org.apache.openjpa.jdbc.sql.DBDictionary(ForUpdateClause='')"/>
    </properties>
  </persistence-unit>
</persistence>
```

### PR DESCRIPTION
**Pull request by eolivelli**
- use a global register for datasources created by the JDBC Driver
- canonicalize the key for each datasource, as OpenJPA calls 'connect' with different Properties objects
- add minimal test case
- implement a few HerdDBResultSet methods
- implement jdbc driver information
- deregistering the driver will close all of the datasources, datatasources that started the embedded server will stop the server
- implement "autoClose" JDBC property, that requests the JDBC driver to autoClose the datasource and stop the embedded database when there is any active connection anymore
- add new OpenJPA DBDictionary for HerdDB in order to tell OpenJPA to escape every identifier and to let it know (un)supported capabilities

Fixes #634

### CODE REVIEW

**Comment by eolivelli** [comment]
Synchronisation is broken

**Comment by eolivelli** [comment]
I have implemented a new "autoClose" mechanism that stops the embedded database when there isn't any connection.
In this PR I have modified the example by using Commons DBCP in order to have a pool of connections (minIdle=1).

The behaviour of OpenJPA is still weird to me:
1)  It still creates a connection and then releases it immediately, this fact shutdowns and restarts the server (losing all of the contents), see the stacktraces below.
2) When the EntityManagerFactory is closed, the DBCP datasource is not closed and thus the number of connections (properly pooled) still stays = 1, and the server is not stopped

Maybe there is something wrong with my OpenJPA configuration.

Stacktraces of the 'priming connection' below 

```
java.lang.Exception: getConnection -> number of active connections is now 1
	at herddb.jdbc.BasicHerdDBDataSource.getConnection(BasicHerdDBDataSource.java:234)
	at herddb.jdbc.BasicHerdDBDataSource.getConnection(BasicHerdDBDataSource.java:225)
	at herddb.jdbc.Driver.connect(Driver.java:129)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at org.apache.openjpa.lib.jdbc.DelegatingDataSource.getConnection(DelegatingDataSource.java:136)
	at org.apache.openjpa.lib.jdbc.DecoratingDataSource.getConnection(DecoratingDataSource.java:94)
	at org.apache.openjpa.jdbc.schema.DataSourceFactory.installDBDictionary(DataSourceFactory.java:250)
	at org.apache.openjpa.jdbc.conf.JDBCConfigurationImpl.getConnectionFactory(JDBCConfigurationImpl.java:806)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.openjpa.lib.conf.ConfigurationImpl.instantiateAll(ConfigurationImpl.java:330)
	at org.apache.openjpa.conf.OpenJPAConfigurationImpl.instantiateAll(OpenJPAConfigurationImpl.java:1963)
	at org.apache.openjpa.kernel.AbstractBrokerFactory.makeReadOnly(AbstractBrokerFactory.java:667)
	at org.apache.openjpa.kernel.AbstractBrokerFactory.newBroker(AbstractBrokerFactory.java:207)
	at org.apache.openjpa.kernel.DelegatingBrokerFactory.newBroker(DelegatingBrokerFactory.java:166)
	at org.apache.openjpa.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:262)
	at org.apache.openjpa.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:177)
	at org.apache.openjpa.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:167)
	at org.apache.openjpa.persistence.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:64)
	at test.SimplyOpenJPATest.hello(SimplyOpenJPATest.java:44)
```
	
	
	
	
```
java.lang.Exception: releaseConnection number of active connections before release is 1 (going now to 0)
	at herddb.jdbc.BasicHerdDBDataSource.releaseConnection(BasicHerdDBDataSource.java:300)
	at herddb.jdbc.HerdDBConnection.close(HerdDBConnection.java:209)
	at org.apache.commons.dbcp.DelegatingConnection.close(DelegatingConnection.java:247)
	at org.apache.commons.dbcp.PoolableConnection.reallyClose(PoolableConnection.java:122)
	at org.apache.commons.dbcp.PoolableConnectionFactory.destroyObject(PoolableConnectionFactory.java:628)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1562)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at org.apache.openjpa.lib.jdbc.DelegatingDataSource.getConnection(DelegatingDataSource.java:136)
	at org.apache.openjpa.lib.jdbc.DecoratingDataSource.getConnection(DecoratingDataSource.java:94)
	at org.apache.openjpa.jdbc.schema.DataSourceFactory.installDBDictionary(DataSourceFactory.java:250)
	at org.apache.openjpa.jdbc.conf.JDBCConfigurationImpl.getConnectionFactory(JDBCConfigurationImpl.java:806)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

**Comment by eolivelli** [comment]
It turns out that DecordatingDatasource implements Closeable, I am investigating

**Comment by rmannibucau** [comment]
@eolivelli if you call entityManagerFactory.close() then the openjpa conf is close and triggers datasource close (org.apache.openjpa.jdbc.conf.JDBCConfigurationImpl#preClose).

**Comment by eolivelli** [comment]
I found an answer to one of my problems:
If I want to use HerdDBEmbeddedDatasource it has to implement  `org.apache.openjpa.lib.util.Closeable` and not `java.io.Closeable`
I did not read the 'import' clause in `ImplHelper`

I am not sure it is good to add such hard dependency to OpenJPA.
I will continue investigating the commons DBCP solution.

**Comment by eolivelli** [comment]
The same problems holds for `org.apache.commons.dbcp.BasicDataSource`

**Comment by eolivelli** [comment]
And without Commons DBPC the test case does not work, because the database is continuously lost at each getConnection/close.

@rmannibucau Do you know what I am missing here ? How can this autoClose help ?
- With Commons DBCP no one closes the datasource
- Without Commons DBCP autoClose is not possible

Are you using H2Database with OpenJPA with autoclose ? or with DB_CLOSE_DELAY=-1 (that is our "leak' case) ? (http://www.h2database.com/html/features.html)

**Comment by eolivelli** [comment]
I could create our own DBDictionary and override `closeDataSource` and handle explicitly DBCP.

I don't know OpenJPA project, is is better to open an issue up there and send a fix for it ?

**Comment by eolivelli** [comment]
I finally managed to see the DBCP datasource closed and the server stopped by implementing my own DBDictionary.
Still it is not the perfect solution, because commons DBCP does that priming connection that start/stops the server

**Comment by rmannibucau** [comment]
@eolivelli hmm, about the dictionary I guess it is better handled in herdb since it will be more reactive there but happy to add it to openjpa too. About the close I don't think you need to do it like that, since dbcp will handle a mindIdle >= 1 there will be a connection until openjpa - or the container for tomee for example - closes dbcp datasource and therefore reset the number of connection to 0. Can it be a pool issue?

**Comment by eolivelli** [comment]
@rmannibucau 
I am sorry but without this block, the DBCP datasource is not closed

https://github.com/diennea/herddb/pull/637/commits/7db0fa7fbbcd12bcbcad1854ec7249d9a26654d2#diff-8cee20119f180e3382608cffd26dcbc7R73

**Comment by eolivelli** [comment]
I am also investigating why even if we add "USER" to the reserved words set it still tries to create a table with name "User"

**Comment by rmannibucau** [comment]
@eolivelli expected flow is to have org.apache.openjpa.kernel.AbstractBrokerFactory#close called when EMF is closed then it calls JDBCConfigurationImpl#preClose which closes the datasource which will empty the pool.

**Comment by eolivelli** [comment]
@rmannibucau you are right
but the BasicDataSource instance flow to here
https://github.com/apache/openjpa/blob/master/openjpa-kernel/src/main/java/org/apache/openjpa/util/ImplHelper.java#L204

and it is not closed

I am investigating with a debugger/breakpoint, I am sure

**Comment by rmannibucau** [comment]
@eolivelli can it be you dont have dbcp in the classpath so a SimpleDataSource is created? this one likely does not work as mentionned (but is a fallback)

**Comment by eolivelli** [comment]
@rmannibucau It looks like I have fixed the issue with identifiers (I just had to force Mysql-style delimiters)

Once we merge this patch we can move forward with more challenges for HerdDB + OpenJPA

thank you very much for your support on Slack !

**Pull request merged**
