### PR TITLE
Upgrade to latest version of Calcite.

### PR DESCRIPTION
**Pull request by amitvc**
All unit tests are successfully passing.

### CODE REVIEW

**Comment by eolivelli** [comment]
Good!
Please add a link to apache snapshots repository, this way we can validate automatically the patch

See this example:
http://activemq.apache.org/maven-snapshot-repository-in-your-pom

**Comment by amitvc** [comment]
Added snapshot repository to pom.xml

**Comment by eolivelli** [comment]
It looks like travis does not still find Calcite.

To test it locally you can nuke your copy of Calcite jars inside $HOME/.m2

**Comment by amitvc** [comment]
@eolivelli will test it tonight.

**Comment by eolivelli** [comment]
Great. Thank you.

**Comment by amitvc** [comment]
@eolivelli You are correct. Once I get rid of my local m2 repository cache for calcite the build does not work. The snapshot repository for calcite https://repository.apache.org/content/repositories/snapshots/org/apache/calcite/ does not have the  built jar in it. I will ping the calcite community to see if they publish the snapshots to maven repository

**Comment by eolivelli** [comment]
@amitvc I didn't see your email to the Calcite list

**Comment by amitvc** [comment]
@eolivelli I sent the email this morning.

**Comment by eolivelli** [comment]
Just closed and opened to kick Travis

**Comment by eolivelli** [comment]
It looks like we have a failing test in backwaed compatibility tests.
It looks like another bug in Calcite

**Comment by eolivelli** [comment]
@amitvc 

did you see this error on Travis ?

```
[INFO] Running herddb.upgrade.UpgradeFrom050WithBrinIndexesTest

[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.466 s - in herddb.upgrade.UpgradeFrom050WithBrinIndexesTest

[INFO] Running herddb.upgrade.RunHerdDB070Test

[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.61 s <<< FAILURE! - in herddb.upgrade.RunHerdDB070Test

[ERROR] test(herddb.upgrade.RunHerdDB070Test)  Time elapsed: 6.393 s  <<< ERROR!

java.lang.StackOverflowError

	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java)

	at com.google.common.collect.SingletonImmutableList.<init>(SingletonImmutableList.java:38)

	at com.google.common.collect.ImmutableList.of(ImmutableList.java:93)

	at org.apache.calcite.rel.SingleRel.getInputs(SingleRel.java:63)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:640)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)

	at org.apache.calcite.plan.volcano.RelSubset$CheapestPlanReplacer.visit(RelSubset.java:644)
```

**Comment by amitvc** [comment]
@eolivelli How do I access travis-ci for our project. I will investigate more and report it Calcite community.

**Comment by eolivelli** [comment]
As you are the owner of the PR you are the owner of the Travis execution instance.
Just clicl on the 'details' link of the failure.
You will have to login in Travis, usually you are using 'login with github' button.

**Comment by aluccaroni** [comment]
@eolivelli I think our travis is visible to the public, since I see the log of the build under https://travis-ci.org/diennea/herddb/builds/605208603

@amitvc  you will find all the pull request build results under https://travis-ci.org/diennea/herddb/pull_requests, but you can also follow the "Details" link near "The Travis CI build failed" ( see "All Checks have failed" just below the comments).

**Comment by amitvc** [comment]
@eolivelli @aluccaroni Found the query that fails in the RunHerdDB070Test.java [line 148]. 

"SELECT * FROM license t0, customer c WHERE c.customer_id = 3 AND t0.customer_id = 3 AND c.customer_id = t0.customer_id\n"

trying to figure out what is happening within Calcite for this.

**Comment by eolivelli** [comment]
@amitvc good.
We have to create  JIRA in Calcite and ask for a fix before the next release otherwise we are still stuck with 1.19

**Comment by amitvc** [comment]
@eolivelli If I remove "AND c.customer_id = t0.customer_id\n" the query works. Would'nt c.customer_id = 3 AND t0.customer_id = 3  this cover it?

**Comment by amitvc** [comment]
I created https://issues.apache.org/jira/browse/CALCITE-3479 for this bug. I will ping on Calcite dev email list.

**Comment by aluccaroni** [comment]
Just closed and opened to kick Travis

**Comment by aluccaroni** [comment]
Kick Travis again

**Comment by eolivelli** [comment]
Tests are now fixed with current Calcite master
INFO] -------------------------------------------------------
[INFO] Running herddb.upgrade.UpgradeFrom050WithBrinIndexesTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.1 s - in herddb.upgrade.UpgradeFrom050WithBrinIndexesTest
[INFO] Running herddb.upgrade.RunHerdDB070Test
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.225 s - in herddb.upgrade.RunHerdDB070Test


great work @amitvc 
let's wait for Calcite release

**Comment by eolivelli** [comment]
We must keep an eye on Calcite, they can still introduce new regressions before the release :-)

**Comment by eolivelli** [comment]
@amitvc please keep this branch in sync with master branch.
We will merge as soon as Calcite community releases 1.22

**Comment by eolivelli** [comment]
@aluccaroni  @amitvc  @diegosalvi 
Travis passed !!

@diegosalvi  It would be good to try some downstream application with this branch, in order to validate the upgrade and report problem to Calcite community.
I can try Pulsar Manager

**Comment by eolivelli** [comment]
@amitvc please keep this branch update-to-date with current master.
We are going to commit it as soon as Calcite 1.22 is released 👍

**Comment by eolivelli** [comment]
@amitvc  can you rebase to latest master when you have time ?

**Comment by amitvc** [comment]
@eolivelli doing this now. Sorry, it took this long.

**Comment by amitvc** [comment]
@eolivelli I rebased the branch.

**Comment by aluccaroni** [comment]
@amitvc  Apache RAT is flagging herddb-core/src/main/java/herddb/sql/CalciteEnumUtils.java becouse of missing License header

**Comment by eolivelli** [comment]
Looks good to me.
But we should hold on, because we cannot depend on a SNAPSHOT version

**Comment by eolivelli** [comment]
@amitvc  they are voting Calcite 1.22 we should give feedback as soon as possible

**Comment by eolivelli** [comment]
In order to test against RC you should use this URL as "repository" instead of "snapshots.apache.org" , and set "<releases>" enabled
https://repository.apache.org/content/repositories/orgapachecalcite-1076
This way Maven will download "staged" artifacts of the RC

**Comment by eolivelli** [comment]
I am seeing this error now:
```
[ERROR] testFencingDuringTransaction(herddb.cluster.bookkeeper.FencingTest)  Time elapsed: 5.227 s  <<< ERROR!
java.lang.RuntimeException: Error while applying rule EnumerableTableScanRule(in:NONE,out:ENUMERABLE), args [rel#16:LogicalTableScan.NONE.[](table=[herd, t1])]
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:244)
	at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:636)
	at herddb.sql.CalcitePlanner.runPlanner(CalcitePlanner.java:520)
	at herddb.sql.CalcitePlanner.translate(CalcitePlanner.java:288)
	at herddb.core.TestUtils.scan(TestUtils.java:70)
	at herddb.cluster.bookkeeper.FencingTest.testFencingDuringTransaction(FencingTest.java:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
	at herddb.sql.CalcitePlanner$TableImpl.getExpression(CalcitePlanner.java:1374)
	at org.apache.calcite.prepare.RelOptTableImpl.lambda$getClassExpressionFunction$2(RelOptTableImpl.java:165)
	at org.apache.calcite.prepare.RelOptTableImpl.getExpression(RelOptTableImpl.java:214)
	at org.apache.calcite.adapter.enumerable.EnumerableTableScanRule.convert(EnumerableTableScanRule.java:63)
	at org.apache.calcite.rel.convert.ConverterRule.onMatch(ConverterRule.java:144)
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:217)
	... 34 more


```

**Comment by eolivelli** [comment]
I have created a new branch  #563

I have fixed that error, but we have serious issue on JOINs

**Comment by eolivelli** [comment]
Closing this PR, superseded by #563

**Pull request closed without merging**
