### PR TITLE
Update jSQLParser to 3.1

### PR DESCRIPTION
**Pull request by eolivelli**
Update jSQLParser to 3.0 and remove deprecated code of legacy pre-Calcite planner.

This is particularly needed in order to be compatible with latest versions of myBatis pagehelper plugin

Release notes:
https://github.com/JSQLParser/JSqlParser/releases/tag/jsqlparser-3.1

> @wumpz wumpz released this 16 days ago · 7 commits to master since this release
> 
> support for cross apply
> allowed keyword character as object name
> allowed keyword size as object name
> introduced FILTER expression for window functions
> allow more complex expressions for CASE.
> allowed start as object name as column name or table name
> introduced more positions for ! instead of NOT
> allowed more complex expressions within if function
> introduced multicolumn alias like select * from mytab as tab(c1, c2)

### CODE REVIEW

**Comment by eolivelli** [comment]
It seems that jsqlparser does not support "RENAME TO" any more

https://github.com/JSQLParser/JSqlParser/issues/860

**Comment by eolivelli** [comment]
WE have to move to 'ALTER TABLE tblspace1.tsql CHANGE k1 l2 int'

**Comment by eolivelli** [comment]
@diegosalvi this patch is good to go

@amitvc FYI

**Comment by eolivelli** [comment]
With this patch a downstream application that uses columns with name 'size' does work anymore,
I have reported an issue upstream to JSQLParser
https://github.com/JSQLParser/JSqlParser/issues/867

**Comment by aluccaroni** [comment]
I see that we have a new release downstream, can we merge?

https://github.com/JSQLParser/JSqlParser/releases/tag/jsqlparser-3.1

**Comment by eolivelli** [comment]
Yes.
In fact now Travis is fine

cc @diegosalvi  @amitvc

**Comment by eolivelli** [comment]
I feel we should add a testcase about the problem we found in EmailSuccess
```
With this patch a downstream application that uses columns with name 'size' does work anymore,
I have reported an issue upstream to JSQLParser
```

**Pull request merged**
