### PR TITLE
Introduce Apache RAT to check license headers

### PR DESCRIPTION
**Pull request by aluccaroni**

### CODE REVIEW

**Comment by aluccaroni** [comment]
Close and open to kick travis

**Comment by eolivelli** [comment]
but RAT failed on Travis :-( 

[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (default-cli) on project herddb-parent: Too many files with unapproved license: 1 See RAT report in: /home/travis/build/diennea/herddb/target/rat.txt -> [Help 1]

**Comment by eolivelli** [comment]
> Close and open to kick travis

You can simply click on "Restart job button" in Travis on the top right

**Comment by eolivelli** [comment]
[WARNING] Files with unapproved licenses:
  herddb-bench/nb-configuration.xml

**Comment by aluccaroni** [comment]
@eolivelli yup, herddb-bench is not tested if we run "mvn apache-rat:check"
Lets wait for CI, but it should be fixed now

**Comment by aluccaroni** [comment]
@eolivelli it's the second time in a row that the build fail on jdbcHugeTableScan

**Comment by aluccaroni** [comment]
@eolivelli  CI passed, do we want to merge before cutting v0.14?

**Pull request merged**
